CREATE TABLE `Roles` (
  `ID` TINYINT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE `Users` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Email` VARCHAR(255) UNIQUE NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Role` TINYINT DEFAULT 1,
  `BlockedStatus` BOOLEAN DEFAULT 0,
  `Name` VARCHAR(255),
  `Surname` VARCHAR(255),
  `PhoneNumber` VARCHAR(255),
  FOREIGN KEY (`Role`) REFERENCES `Roles`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `TourTypes` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(255) UNIQUE NOT NULL,
  `PathToImage` VARCHAR(255)
);

CREATE TABLE `Regions` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL,
  `PathToImage` VARCHAR(255)
);

CREATE TABLE `Countries` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL,
  `PathToFlag` VARCHAR(255),
  `RegionId` INT,
  FOREIGN KEY (`RegionId`) REFERENCES `Regions`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `Cities` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL,
  `CountryId` INT,
  FOREIGN KEY (`CountryId`) REFERENCES `Countries`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `TransportTypes` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE `DepartmentDepartures` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL,
  `CityId` INT,
  `Address` VARCHAR(255),
  `TransportTypeId` INT,
  `Lat` DOUBLE,
  `Lng` DOUBLE,
  FOREIGN KEY (`CityId`) REFERENCES `Cities`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`TransportTypeId`) REFERENCES `TransportTypes`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `NutritionTypes` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE `Hotels` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL,
  `CityId` INT,
  `Address` VARCHAR(255),
  `StarsNumber` INT NOT NULL,
  `MainDescription` VARCHAR(255),
  `NutritionTypeId` INT,
  `Lat` DOUBLE,
  `Lng` DOUBLE,
  FOREIGN KEY (`CityId`) REFERENCES `Cities`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`NutritionTypeId`) REFERENCES `NutritionTypes`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `HotelCharacteristics` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE `HotelDescriptions` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `CharacteristicID` INT,
  `HotelID` INT,
  FOREIGN KEY (`CharacteristicID`) REFERENCES `HotelCharacteristics`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`HotelID`) REFERENCES `Hotels`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `RoomTypes` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `Price` INT,
  `SeatsNumber` INT,
  `RoomsNumber` INT,
  `HotelId` INT,
  FOREIGN KEY (`HotelId`) REFERENCES `Hotels`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `RoomTypeCharacteristics` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE `RoomTypeDescriptions` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `CharacteristicID` INT,
  `RoomTypeID` INT,
  FOREIGN KEY (`CharacteristicID`) REFERENCES `RoomTypeCharacteristics`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`RoomTypeID`) REFERENCES `RoomTypes`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `Tours` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(255) UNIQUE NOT NULL,
  `MainDescription` VARCHAR(255),
  `TourTypeId` INT,
  `HotelId` INT,
  FOREIGN KEY (`TourTypeId`) REFERENCES `TourTypes`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`HotelId`) REFERENCES `Hotels`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `TourCharacteristics` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NAME` VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE `TourDescriptions` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `CharacteristicID` INT,
  `TourID` INT,
  FOREIGN KEY (`CharacteristicID`) REFERENCES `TourCharacteristics`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`TourID`) REFERENCES `Tours`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `Reviews` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `UserId` INT,
  `TourId` INT,
  `ReviewText` VARCHAR(255),
  FOREIGN KEY (`UserId`) REFERENCES `Users`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`TourId`) REFERENCES `Tours`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `Routes` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `LandingDateOfDeparture` DATE,
  `LandingTimeOfDeparture` TIME,
  `ArrivalDateOfDeparture` DATE,
  `ArrivalTimeOfDeparture` TIME,
  `LandingDateOfReturn` DATE,
  `LandingTimeOfReturn` TIME,
  `ArrivalDateOfReturn` DATE,
  `ArrivalTimeOfReturn` TIME,
  `Price` INT,
  `SeatsNumber` INT,
  `DepartmentDepartureId` INT,
  `TourId` INT,
  FOREIGN KEY (`DepartmentDepartureId`) REFERENCES `DepartmentDepartures`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`TourId`) REFERENCES `Tours`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `Bookings` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `OrderSeatsNumber` INT,
  `UserId` INT,
  `RouteId` INT,
  `Price` INT,
  `Status` BOOLEAN DEFAULT 0,
  `Comment` VARCHAR(255),
  `HasСhildren` BOOLEAN DEFAULT 0,
  `PrioritySeatsInTransport` BOOLEAN DEFAULT 0,
  FOREIGN KEY (`UserId`) REFERENCES `Users`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`RouteId`) REFERENCES `Routes`(`ID`) ON DELETE CASCADE
);

CREATE TABLE `BookedRoomTypes` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `RoomTypeID` INT,
  `BookingID` INT,
  `OrderRoomsNumber` INT,
  FOREIGN KEY (`RoomTypeID`) REFERENCES `RoomTypes`(`ID`) ON DELETE CASCADE,
  FOREIGN KEY (`BookingID`) REFERENCES `Bookings`(`ID`) ON DELETE CASCADE
);
